=== 1313ou/schemas/WN-LMF.dtd
<?xml version='1.0' encoding="UTF-8"?>
<!ELEMENT LexicalResource (Lexicon+)>
<!ELEMENT Lexicon (LexicalEntry+, Synset*, Meta?)>
<!ATTLIST Lexicon
    id ID #REQUIRED
    label CDATA #REQUIRED
    language CDATA #REQUIRED
    email CDATA #REQUIRED
    license CDATA #REQUIRED
    version CDATA #REQUIRED
    url CDATA #IMPLIED
    citation CDATA #IMPLIED>
<!ELEMENT LexicalEntry (Lemma, Sense*, SyntacticBehaviour*, Meta?)>
<!ATTLIST LexicalEntry
    id ID #REQUIRED>
<!ELEMENT Lemma EMPTY>
<!ATTLIST Lemma
    writtenForm CDATA #REQUIRED
    partOfSpeech (n|v|a|r|s|p|u) #REQUIRED>
<!ELEMENT Sense (SenseRelation*, SenseExample*, Meta?)>
<!ATTLIST Sense
    id ID #REQUIRED
    synset IDREF #REQUIRED>
<!ELEMENT Synset (Definition*, ILIDefinition?, SynsetRelation*, Meta?)>
<!ATTLIST Synset
    id ID #REQUIRED
    ili CDATA #REQUIRED>
<!ELEMENT Definition Meta?>
<!ATTLIST Definition
    language CDATA #IMPLIED
    gloss CDATA #REQUIRED>
<!ELEMENT ILIDefinition Meta?>
<!ATTLIST ILIDefinition
    gloss CDATA #REQUIRED>
<!ELEMENT SenseExample Meta?>
<!ATTLIST SenseExample
    example CDATA #REQUIRED>
<!ELEMENT SynsetRelation Meta?>
<!ATTLIST SynsetRelation
    target IDREF #REQUIRED
    relType (hypernym|hyponym|instance_hypernym|instance_hyponym|part_holonym|part_meronym|member_holonym|member_meronym|substance_holonym|substance_meronym|entail|cause|similar|also|attribute|verb_group|domain_category|domain_member_category|domain_region|domain_member_region|domain_usage|domain_member_usage|action|theme|product|location|agent|instrument|result|patient|beneficiary|creator|goal|experiencer) #REQUIRED>
<!ELEMENT SenseRelation Meta?>
<!ATTLIST SenseRelation
    target IDREF #REQUIRED
    relType (antonym|also|verb_group|participle|pertainym|derivation|domain_category|domain_member_category|domain_region|domain_member_region|domain_usage|domain_member_usage) #REQUIRED>
<!ELEMENT SyntacticBehaviour EMPTY>
<!ATTLIST SyntacticBehaviour
  subcategorizationFrame CDATA #REQUIRED>
<!ELEMENT Meta EMPTY>
<!ATTLIST Meta
    contributor CDATA #IMPLIED
    coverage CDATA #IMPLIED
    creator CDATA #IMPLIED
    date CDATA #IMPLIED
    description CDATA #IMPLIED
    format CDATA #IMPLIED
    identifier CDATA #IMPLIED
    language CDATA #IMPLIED
    publisher CDATA #IMPLIED
    relation CDATA #IMPLIED
    rights CDATA #IMPLIED
    source CDATA #IMPLIED
    subject CDATA #IMPLIED
    title CDATA #IMPLIED
    type CDATA #IMPLIED
    status CDATA #IMPLIED
    confidenceScore CDATA #IMPLIED>

=== 1313ou/schemas/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LexicalResource SYSTEM "http://globalwordnet.github.io/schemas/WN-LMF.dtd">
<LexicalResource>
    <Lexicon label="Princeton WordNet" language="eng">
        <LexicalEntry id="w1">
            <Lemma writtenForm="entity" partOfSpeech="n"/>
            <Sense id="pwn-100001740-n-1" synset="pwn-100001740-n"/>
        </LexicalEntry>
        <LexicalEntry id="w2">
            <Lemma writtenForm="able" partOfSpeech="a"/>
            <Sense id="pwn-300001740-a-1" synset="pwn-300001740-a">
                <SenseRelation relType="antonym" target="pwn-300002908-a-1"/>
            </Sense>
        </LexicalEntry>
        <Synset id="pwn-100001740-n" ili="i35545">
            <Definition gloss="that which is perceived or known or inferred to have its own distinct existence (living or nonliving)" iliDef=""/>
            <SynsetRelation relType="hyponym" target="pwn-104431553-n"/>
            <SynsetRelation relType="hyponym" target="pwn-100002137-n"/>
            <SynsetRelation relType="hyponym" target="pwn-100001930-n"/>
        </Synset>
        <Synset id="pwn-300001740-a" ili="i1">
            <Definition gloss="(usually followed by `to') having the necessary means or skill or know-how or authority to do something" iliDef=""/>
            <SynsetRelation relType="attribute" target="pwn-105624029-n"/>
            <SynsetRelation relType="attribute" target="pwn-105204437-n"/>
        </Synset>
        <Meta
            publisher="Global Wordnet Association"
            description="Example lexicon" />
    </Lexicon>
</LexicalResource>
